### ISSUE TITLE
Price Checker doesnt work properly

### ISSUE THREAD

**Issue by CokkocZateki** [shibdib/Dramiel#70]
Hi. 
If i use the entry !pc ibis it spits out 

```

Buy:
   Low: 112.97
   Avg: 655.23
   High: 125,917.38
Sell:
   Low: 1.00
   Avg: 38,931.80
   High: 250,000.00
```

however if i specify a trade i with !pc Jita ibis i get

```
Buy:
   Low: 0.00
   Avg: 0.00
   High: 0.00
Sell:
   Low: 0.00
   Avg: 0.00
   High: 0.00
```

any idea why its doing this?
